program SAO;

uses
  Forms,
  sysutils,
  Controls,
  Utama in 'Utama.pas' {fmUtama},
  StdLv0 in 'Form Template\StdLv0.pas' {fmStdLv0},
  StdLv1 in 'Form Template\StdLv1.pas' {fmStdLv1},
  StdLv2 in 'Form Template\StdLv2.pas' {fmStdLv2},
  ConMain in 'Unit\ConMain.pas' {dmMain: TDataModule},
  StdLv3 in 'Form Template\StdLv3.pas' {fmStdLv3},
  StdLv31 in 'Form Template\StdLv31.pas' {fmStdLv31},
  StdLv4 in 'Form Template\StdLv4.pas' {fmStdLv4},
  StdLv01 in 'Form Template\StdLv01.pas' {fmStdLv01},
  StdLv011 in 'Form Template\StdLv011.pas' {fmStdLv011},
  PeriodDlg in 'Form Template\PeriodDlg.pas' {fmPeriodDlg},
  UnitDate in 'Unit\UnitDate.pas',
  Search in 'Unit\Search.pas' {fmSearch},
  UnitDatabase in 'Unit\UnitDatabase.pas',
  UnitGeneral in 'Unit\UnitGeneral.pas',
  RptDlg1 in 'Form Template\RptDlg1.pas' {fmRptDlg1},
  RptDlg2 in 'Form Template\RptDlg2.pas' {fmRptDlg2},
  RptDlg3 in 'Form Template\RptDlg3.pas' {fmRptDlg3},
  StdLv41 in 'Form Template\StdLv41.pas' {fmStdLv41},
  SetSecurityAccess in 'Bin\Setting\Setup\SetSecurityAccess.pas' {fmSetSecurityAccess},
  Login in 'Bin\Login.pas' {fmLogin},
  MyUnit in 'Unit\MyUnit.pas',
  MemoDlg in 'Form Template\MemoDlg.pas' {fmShowDlg},
  RptLv0 in 'Report Template\RptLv0.pas' {fmRptLv0},
  RptLv1 in 'Report Template\RptLv1.pas' {fmRptLv1},
  RptLv2 in 'Report Template\RptLv2.pas' {fmRptLv2},
  PassChange in 'Unit\PassChange.pas' {fmPassChange},
  RptDlg in 'Form Template\RptDlg.pas' {fmRptDlg},
  RptLv3 in 'Report Template\RptLv3.pas' {fmRptLv3},
  RptLv4 in 'Report Template\RptLv4.pas' {fmRptLv4},
  APMsSupplier in 'Bin\AP\Setup\APMsSupplier.pas' {fmAPMsSupplier},
  ARMsSales in 'Bin\AR\Setup\ARMsSales.pas' {fmARMsSales},
  INMsUOM in 'Bin\Inventory\Setup\INMsUOM.pas' {fmINMsUOM},
  INMsProduct in 'Bin\Inventory\Setup\INMsProduct.pas' {fmINMsProduct},
  INMsGroup in 'Bin\Inventory\Setup\INMsGroup.pas' {fmINMsGroup},
  INMsItem in 'Bin\Inventory\Setup\INMsItem.pas' {fmINMSItem},
  INMsWareHouse in 'Bin\Inventory\Setup\INMsWareHouse.pas' {fmINMsWareHouse},
  INTrAdjustment in 'Bin\Inventory\Activities\INTrAdjustment.pas' {fmINTrAdjustment},
  INTransfer in 'Bin\Inventory\Activities\INTransfer.pas' {fmINTransfer},
  Allitem in 'Bin\Allitem.pas',
  APPurchaseOrder in 'Bin\AP\Activities\APPurchaseOrder.pas' {fmAPPurchaseOrder},
  APRetur in 'Bin\AP\Activities\APRetur.pas' {fmAPRetur},
  APPenggantiRetur in 'Bin\AP\Activities\APPenggantiRetur.pas' {fmAPPenggantiRetur},
  APKonsinyasi in 'Bin\AP\Activities\APKonsinyasi.pas' {fmAPKonsinyasi},
  APKonsinyasiInvIDR in 'Bin\AP\Activities\APKonsinyasiInvIDR.pas' {fmAPKonsinyasiInvIDR},
  APPembayaranKonsIDR in 'Bin\AP\Activities\APPembayaranKonsIDR.pas' {fmAPPembayaranKonsIDR},
  APReturKon in 'Bin\AP\Activities\APReturKon.pas' {fmAPReturKon},
  ARTrKonInvPelIDR in 'Bin\AR\Activities\ARTrKonInvPelIDR.pas' {fmARTrKonInvPelIDR},
  ARTrKonPiutangIDR in 'Bin\AR\Activities\ARTrKonPiutangIDR.pas' {fmARTrKonPiutangIDR},
  ARTrKonRetur in 'Bin\AR\Activities\ARTrKonRetur.pas' {fmARTrKonRetur},
  ARTrKonTransBrg in 'Bin\AR\Activities\ARTrKonTransBrg.pas' {fmARTrKonTransBrg},
  ARTrPenjualanIDR in 'Bin\AR\Activities\ARTrPenjualanIDR.pas' {fmARTrPenjualanIDR},
  ARTrPiutangIDR in 'Bin\AR\Activities\ARTrPiutangIDR.pas' {fmARTrPiutangIDR},
  SAMsCompany in 'Bin\Setup Acc\Setup\SAMsCompany.pas' {fmSAMsCompany},
  ARQRRptSegel in 'Bin\AR\Report\ARQRRptSegel.pas' {fmQRRptSegel},
  ARQRRptInvPenjualan in 'Bin\AR\Report\ARQRRptInvPenjualan.pas' {fmQRRptInvPenjualan},
  ARQRRptSuratJalan in 'Bin\AR\Report\ARQRRptSuratJalan.pas' {fmQRRptSuratJalan},
  SetWareHouse in 'Bin\Setting\Setup\SetWareHouse.pas' {fmSettingGudang},
  Keypad in 'Bin\Keypad.pas' {fmKeyPad},
  ARTrTerimaService in 'Bin\AR\Activities\ARTrTerimaService.pas' {fmARTrService},
  ARMsTeknisi in 'Bin\AR\Setup\ARMsTeknisi.pas' {fmARMsTeknisi},
  INQRRptHistoryStok in 'Bin\Inventory\Report\INQRRptHistoryStok.pas' {fmINQRRptHistoryStok},
  INRptHistoryStokDlg in 'Bin\Inventory\Report\INRptHistoryStokDlg.pas' {fmINRptHistoryBarangDlg},
  QRRptINStok in 'Bin\Inventory\Report\QRRptINStok.pas' {fmINQRRptStok},
  RptINStokDlg in 'Bin\Inventory\Report\RptINStokDlg.pas' {fmINRptStokDlg},
  SAMsValuta in 'Bin\Setup Acc\Setup\SAMsValuta.pas' {fmSAMsValuta},
  APPembayaranHutangPengRet in 'Bin\AP\Activities\APPembayaranHutangPengRet.pas' {fmAPPayReturnRep},
  ARTrSC in 'Bin\AR\Activities\ARTrSC.pas' {fmSC},
  ARSearchSC in 'Bin\AR\Activities\ARSearchSC.pas' {fmSearchSales},
  ARQRRptStokAkhir in 'Bin\AR\Report\ARQRRptStokAkhir.pas' {fmINQRRptStokAkhir},
  QRRptINStokMinim in 'Bin\Inventory\Report\QRRptINStokMinim.pas' {fmINQRRptStokMinim},
  INRpMsItemDlg in 'Bin\Inventory\Report\INRpMsItemDlg.pas' {fmINRptMsItemDlg},
  INQRRptMsItem in 'Bin\Inventory\Report\INQRRptMsItem.pas' {fmINQRRptMsItem},
  INRpPriceListDlg in 'Bin\Inventory\Report\INRpPriceListDlg.pas' {fmINRptPriceListDlg},
  INQRRptPriceList in 'Bin\Inventory\Report\INQRRptPriceList.pas' {fmINQRRptPriceList},
  INRptAdjusmentDlg in 'Bin\Inventory\Report\INRptAdjusmentDlg.pas' {fmINRptAdjustmentDlg},
  INQRRptAdjusment in 'Bin\Inventory\Report\INQRRptAdjusment.pas' {fmINQRRptAdjusment},
  INQRRptTransferBarang in 'Bin\Inventory\Report\INQRRptTransferBarang.pas' {fmINQRRptTransferBarang},
  INRptTransferBarangDlg in 'Bin\Inventory\Report\INRptTransferBarangDlg.pas' {fmINRptTransferBarangDlg},
  APQRRptTerimaBarang in 'Bin\AP\Report\APQRRptTerimaBarang.pas' {fmAPQRRptTerimaBarang},
  APRptTerimaBarangDlg in 'Bin\AP\Report\APRptTerimaBarangDlg.pas' {fmAPRptTerimaBarangDlg},
  ARQRRptTransferBarang in 'Bin\AR\Report\ARQRRptTransferBarang.pas' {fmARQRRptTransferBarang},
  ARRptTransferBarangDlg in 'Bin\AR\Report\ARRptTransferBarangDlg.pas' {fmARRptTransferBarangDlg},
  APRptSisaTerimaBarangDlg in 'Bin\AP\Report\APRptSisaTerimaBarangDlg.pas' {fmAPRptSisaTerimaBarangDlg},
  APQRRptSisaTerimaBarang in 'Bin\AP\Report\APQRRptSisaTerimaBarang.pas' {fmAPQRRptSisaTerimaBarang},
  ARQRRptSisaTransferBarang in 'Bin\AR\Report\ARQRRptSisaTransferBarang.pas' {fmARQRRptSisaTransferBarang},
  ARRptSisaTransferBarangDlg in 'Bin\AR\Report\ARRptSisaTransferBarangDlg.pas' {fmARRptSisaTransferBarangDlg},
  ARSN in 'Bin\AR\Activities\ARSN.pas' {fmARSN},
  APRptRtrBlmGntDlg in 'Bin\AP\Report\APRptRtrBlmGntDlg.pas' {fmAPRptRtrBlmGntDlg},
  APQRRptRtrBlmGnt in 'Bin\AP\Report\APQRRptRtrBlmGnt.pas' {fmAPQRRptRtrBlmGnt},
  ARRptRtrBlmGntDlg in 'Bin\AR\Report\ARRptRtrBlmGntDlg.pas' {fmARRptRtrBlmGntDlg},
  ARQRRptRtrBlmGnt in 'Bin\AR\Report\ARQRRptRtrBlmGnt.pas' {fmARQRRptRtrBlmGnt},
  ARQRRptTrService in 'Bin\AR\Report\ARQRRptTrService.pas' {fmARQRRptService},
  ARRptTrInvServiceDlg in 'Bin\AR\Report\ARRptTrInvServiceDlg.pas' {fmARRptInvServiceDlg},
  ARQRRptTrInvService in 'Bin\AR\Report\ARQRRptTrInvService.pas' {fmARQRRptInvService},
  APRptReturDlg in 'Bin\AP\Report\APRptReturDlg.pas' {fmAPRptReturPbDlg},
  APQRRptRetur in 'Bin\AP\Report\APQRRptRetur.pas' {fmAPQRRptReturPb},
  ARQRRptRetur in 'Bin\AR\Report\ARQRRptRetur.pas' {fmARQRRptReturPj},
  ARRptReturDlg in 'Bin\AR\Report\ARRptReturDlg.pas' {fmARRptReturPjDlg},
  APRptPembPerTglDlg in 'Bin\AP\Report\APRptPembPerTglDlg.pas' {fmAPRptPembPerTglDlg},
  APQRRptPembPerTgl in 'Bin\AP\Report\APQRRptPembPerTgl.pas' {fmAPQRRptPembPerTgl},
  APRptPembPerBrgDlg in 'Bin\AP\Report\APRptPembPerBrgDlg.pas' {fmAPRptPembPerBrgDlg},
  APQRRptPembPerBrg in 'Bin\AP\Report\APQRRptPembPerBrg.pas' {fmAPQRRptPembPerBrg},
  APQRRptPembPerSupp in 'Bin\AP\Report\APQRRptPembPerSupp.pas' {fmAPQRRptPembPerSupp},
  APRptPembPerSuppDlg in 'Bin\AP\Report\APRptPembPerSuppDlg.pas' {fmAPRptPembPerSuppDlg},
  ARRptPenjPerTglDlg in 'Bin\AR\Report\ARRptPenjPerTglDlg.pas' {fmARRptPenjPerTglDlg},
  ARQRRptPenjPerTgl in 'Bin\AR\Report\ARQRRptPenjPerTgl.pas' {fmARQRRptPenjPerTgl},
  ARRptPenjPerBrgDlg in 'Bin\AR\Report\ARRptPenjPerBrgDlg.pas' {fmARRptPenjPerBrgDlg},
  ARQRRptPenjPerBrg in 'Bin\AR\Report\ARQRRptPenjPerBrg.pas' {fmARQRRptPenjPerBrg},
  ARRptPenjPerCustDlg in 'Bin\AR\Report\ARRptPenjPerCustDlg.pas' {fmARRptPenjPerCustDlg},
  ARQRRptPenjPerCust in 'Bin\AR\Report\ARQRRptPenjPerCust.pas' {fmARQRRptPenjPerCust},
  ARQRRptStruck in 'Bin\AR\Report\ARQRRptStruck.pas' {fmARRptStruck},
  ARQRRptNotaService in 'Bin\AR\Report\ARQRRptNotaService.pas' {fmARQRRptNotaService},
  ARQRRptSparePart in 'Bin\AR\Report\ARQRRptSparePart.pas' {fmARQRRptSparePart},
  ARQRRptInvService in 'Bin\AR\Report\ARQRRptInvService.pas' {fmQRRptInvService},
  ARQRRptBuktiBayar in 'Bin\AR\Report\ARQRRptBuktiBayar.pas' {fmQRRptBuktiBayar},
  RptAPKartuHutangDlg in 'Bin\AP\Report\RptAPKartuHutangDlg.pas' {fmAPRptKartuHutangDlg},
  QRRptAPKartuHutang in 'Bin\AP\Report\QRRptAPKartuHutang.pas' {fmAPQRRptKartuHutang},
  RptAPKartuHutangDetilDlg in 'Bin\AP\Report\RptAPKartuHutangDetilDlg.pas' {fmAPRptKartuHutangDetilDlg},
  QRRptAPKartuHutangDetil in 'Bin\AP\Report\QRRptAPKartuHutangDetil.pas' {fmAPQRRptKartuHutangDetil},
  ARQRRptKartuPiutang in 'Bin\AR\Report\ARQRRptKartuPiutang.pas' {fmARQRRptKartuPiutang},
  ARRptKartuPiutangDlg in 'Bin\AR\Report\ARRptKartuPiutangDlg.pas' {fmARRptKartuPiutangDlg},
  ARRptKartuPiutangDetilDlg in 'Bin\AR\Report\ARRptKartuPiutangDetilDlg.pas' {fmARRptKartuPiutangDetilDlg},
  ARQRRptKartuPiutangDetil in 'Bin\AR\Report\ARQRRptKartuPiutangDetil.pas' {fmARQRRptKartuPiutangDetil},
  QRRptAPKartuHutangPR in 'Bin\AP\Report\QRRptAPKartuHutangPR.pas' {fmAPQRRptKartuHutangPR},
  RptAPKartuHutangPRDlg in 'Bin\AP\Report\RptAPKartuHutangPRDlg.pas' {fmAPRptKartuHutangPRDlg},
  QRRptAPKartuHutangDetilPR in 'Bin\AP\Report\QRRptAPKartuHutangDetilPR.pas' {fmAPQRRptKartuHutangDetilPR},
  RptAPKartuHutangDetilPRDlg in 'Bin\AP\Report\RptAPKartuHutangDetilPRDlg.pas' {fmAPRptKartuHutangDetilPRDlg},
  ARQRRptKartuHutangService in 'Bin\AR\Report\ARQRRptKartuHutangService.pas' {fmARQRRptPiutangService},
  ARRptKartuHutangServiceDlg in 'Bin\AR\Report\ARRptKartuHutangServiceDlg.pas' {fmARRptKartuPiutangServiceDlg},
  ARQRRptKartuPiutangDetilService in 'Bin\AR\Report\ARQRRptKartuPiutangDetilService.pas' {fmARQRRptKartuPiutangDetilService},
  ARRptKartuPiutangDetilServiceDlg in 'Bin\AR\Report\ARRptKartuPiutangDetilServiceDlg.pas' {fmARRptKartuPiutangDetilServiceDlg},
  ARQRRptInvPR in 'Bin\AR\Report\ARQRRptInvPR.pas' {fmQRRptInvPR},
  ARQRRptPenjPerSales in 'Bin\AR\Report\ARQRRptPenjPerSales.pas' {fmARQRRptPenjPerSales},
  ARRptPenjPerSalesDlg in 'Bin\AR\Report\ARRptPenjPerSalesDlg.pas' {fmARRptPenjPerSalesDlg},
  ARQRRptTrInvServicePerTeknisi in 'Bin\AR\Report\ARQRRptTrInvServicePerTeknisi.pas' {fmARQRRptInvServicePerTeknisi},
  ARRptTrInvServicePerTeknisiDlg in 'Bin\AR\Report\ARRptTrInvServicePerTeknisiDlg.pas' {fmARRptInvServicePerTeknisiDlg},
  ARRptKartuTunggakPiutangDlg in 'Bin\AR\Report\ARRptKartuTunggakPiutangDlg.pas' {fmARRptKartuTunggakPiutangDlg},
  ARQRRptKartuTunggakPiutang in 'Bin\AR\Report\ARQRRptKartuTunggakPiutang.pas' {fmARQRRptKartuTunggakPiutang},
  ARQRRptKartuPiutangPR in 'Bin\AR\Report\ARQRRptKartuPiutangPR.pas' {fmARQRRptKartuPiutangPR},
  ARRptKartuPiutangPRDlg in 'Bin\AR\Report\ARRptKartuPiutangPRDlg.pas' {fmARRptKartuPiutangPRDlg},
  ARQRRptKartuPiutangPRDetil in 'Bin\AR\Report\ARQRRptKartuPiutangPRDetil.pas' {fmARQRRptKartuPiutangPRDetil},
  ARRptKartuPiutangPRDetilDlg in 'Bin\AR\Report\ARRptKartuPiutangPRDetilDlg.pas' {fmARRptKartuPiutangPRDetilDlg},
  QRRptAPKartuHutangKonsinyasi in 'Bin\AP\Report\QRRptAPKartuHutangKonsinyasi.pas' {fmAPQRRptKartuHutangKonsinyasi},
  RptAPKartuHutangKonsinyasiDlg in 'Bin\AP\Report\RptAPKartuHutangKonsinyasiDlg.pas' {fmAPRptKartuHutangKonsinyasiDlg},
  RptAPKartuHutangKonsinyasiDetilDlg in 'Bin\AP\Report\RptAPKartuHutangKonsinyasiDetilDlg.pas' {fmAPRptKartuHutangDetilKonsinyasiDlg},
  QRRptAPKartuHutangKonsinyasiDetil in 'Bin\AP\Report\QRRptAPKartuHutangKonsinyasiDetil.pas' {fmAPQRRptKartuHutangKonsinyasiDetil},
  ARQRRptKartuPiutangKonsinyasi in 'Bin\AR\Report\ARQRRptKartuPiutangKonsinyasi.pas' {fmARQRRptKartuPiutangKonsinyasi},
  RptARKartuPiutangKonsinyasiDetilDlg in 'Bin\AR\Report\RptARKartuPiutangKonsinyasiDetilDlg.pas' {fmARRptKartupiutangDetilKonsinyasiDlg},
  ARQRRptKartuPiutangKonsinyasiDetil in 'Bin\AR\Report\ARQRRptKartuPiutangKonsinyasiDetil.pas' {fmARQRRptKartuPiutangKonsinyasiDetil},
  ARRptKartuTunggakPiutangKonsDlg in 'Bin\AR\Report\ARRptKartuTunggakPiutangKonsDlg.pas' {fmARRptKartuTunggakPiutangKonsDlg},
  ARQRRptKartuTunggakPiutangKons in 'Bin\AR\Report\ARQRRptKartuTunggakPiutangKons.pas' {fmARQRRptKartuTunggakPiutangKons},
  ARRptKartuTunggakPiutangServisDlg in 'Bin\AR\Report\ARRptKartuTunggakPiutangServisDlg.pas' {fmARRptKartuTunggakPiutangServisDlg},
  ARQRRptKartuTunggakPiutangServis in 'Bin\AR\Report\ARQRRptKartuTunggakPiutangServis.pas' {fmARQRRptKartuTunggakPiutangServis},
  ARQRRptStruck1 in 'Bin\AR\Report\ARQRRptStruck1.pas' {fmARRptStruck1},
  KeypadDec in 'Bin\KeypadDec.pas' {fmKeyPadDec},
  INRptHPPDlg in 'Bin\Inventory\Report\INRptHPPDlg.pas' {fmINRptHppDlg},
  INQRRptHPP in 'Bin\Inventory\Report\INQRRptHPP.pas' {fmINQRRptHpp},
  RptPrev in 'Report Template\RptPrev.pas' {fmRptPrev},
  QRExportExtra in 'Report Template\QRExportExtra.pas',
  INQRRptLBRG in 'Bin\Inventory\Report\INQRRptLBRG.pas' {fmINQRRptLBRG},
  INRptLBRGDlg in 'Bin\Inventory\Report\INRptLBRGDlg.pas' {fmINRptLBRGDlg},
  CFMsGroupRek in 'Bin\CF\Setup\CFMsGroupRek.pas' {fmCFMsGroupRek},
  CFMsRekening in 'Bin\CF\Setup\CFMsRekening.pas' {fmCFMsRekening},
  CFMsBank in 'Bin\CF\Setup\CFMsBank.pas' {fmCFMsBank},
  CFTrKKBB in 'Bin\CF\Activities\CFTrKKBB.pas' {fmCFTrKKBB},
  CFRptKeuanganDlg in 'Bin\CF\Report\CFRptKeuanganDlg.pas' {fmCFRptKeuanganDlg},
  CFQRRptKeuanganDlg in 'Bin\CF\Report\CFQRRptKeuanganDlg.pas' {fmCFQRRptKeuangan},
  CFRptKeuanganDetDlg in 'Bin\CF\Report\CFRptKeuanganDetDlg.pas' {fmCFRptKeuanganDetDlg},
  CFQRRptKeuanganDet in 'Bin\CF\Report\CFQRRptKeuanganDet.pas' {fmCFQRRptKeuanganDet},
  ARQRRptKomisiSales in 'Bin\AR\Report\ARQRRptKomisiSales.pas' {fmARQRRptKomisiSales},
  RptGLTrKMKK in 'Bin\CF\Report\RptGLTrKMKK.pas' {fmCFQRRptTrKKBB},
  CFRptKeuanganBankDlg in 'Bin\CF\Report\CFRptKeuanganBankDlg.pas' {fmCFRptKeuanganBankDlg},
  CFQRRptKeuanganBank in 'Bin\CF\Report\CFQRRptKeuanganBank.pas' {fmCFQRRptKeuanganBank},
  CFQRRptKeuanganDetBank in 'Bin\CF\Report\CFQRRptKeuanganDetBank.pas' {fmCFQRRptKeuanganDetBank},
  CFRptKeuanganDetBankDlg in 'Bin\CF\Report\CFRptKeuanganDetBankDlg.pas' {fmCFRptKeuanganDetBankDlg},
  ARRptPenjPerProductDlg in 'Bin\AR\Report\ARRptPenjPerProductDlg.pas' {fmARRptPenjPerProductDlg},
  ARQRRptPenjPerProduct in 'Bin\AR\Report\ARQRRptPenjPerProduct.pas' {fmARQRRptPenjPerProduct},
  ARTrBayar in 'Bin\AR\Activities\ARTrBayar.pas' {fmArTrBayar},
  KeypadSC in 'Bin\KeypadSC.pas' {fmKeyPadSC},
  ARRptSummaryKeuanganDlg in 'Bin\AR\Report\ARRptSummaryKeuanganDlg.pas' {fmRptSummaryKeuangan},
  ARQRRptSummaryKeuangan in 'Bin\AR\Report\ARQRRptSummaryKeuangan.pas' {fmINQRRptSummaryK},
  ARRptTrStServiceDlg in 'Bin\AR\Report\ARRptTrStServiceDlg.pas' {fmARRptStServiceDlg},
  ARQRRptTrStService in 'Bin\AR\Report\ARQRRptTrStService.pas' {fmARQRRptStService},
  APRptKartuTunggakanHutangDlg in 'Bin\AP\Report\APRptKartuTunggakanHutangDlg.pas' {fmAPRptKartuTunggakHutangDlg},
  APQRRptAPKartuTunggakanHutang in 'Bin\AP\Report\APQRRptAPKartuTunggakanHutang.pas' {fmAPQRRptKartuTunggakHutang},
  ARQRRptStruck2 in 'Bin\AR\Report\ARQRRptStruck2.pas' {fmARRptStruck2},
  BackUp in 'Bin\BackUp.pas' {fmBackUp},
  ARRptBukuBesarPiutangDlg in 'Bin\AR\Report\ARRptBukuBesarPiutangDlg.pas' {fmARRptBukuBesarPiutangDlg},
  ARQRRptBukuBesar in 'Bin\AR\Report\ARQRRptBukuBesar.pas' {fmARQRRptBukuBesar},
  INRptUmurBarangDlg in 'Bin\Inventory\Report\INRptUmurBarangDlg.pas' {fmINRptUmurBarangDlg},
  INQRRptUmurBarang in 'Bin\Inventory\Report\INQRRptUmurBarang.pas' {fmINQRRptUmurBarang},
  Absensi in 'Bin\Absensi.pas' {fmAbsensi},
  ARQRRptAbsensi in 'Bin\AR\Report\ARQRRptAbsensi.pas' {fmARQRRptAbsensi},
  ARRptPenjPerCustTunaiDlg in 'Bin\AR\Report\ARRptPenjPerCustTunaiDlg.pas' {fmARRptPenjPerCustTunaiDlg},
  ARQRRptPenjPerCustTunai in 'Bin\AR\Report\ARQRRptPenjPerCustTunai.pas' {fmARQRRptPenjPerCustTunai},
  INQRRptLBRGInvoice in 'Bin\Inventory\Report\INQRRptLBRGInvoice.pas',
  CFRptBiayaDlg in 'Bin\CF\Report\CFRptBiayaDlg.pas' {fmCFRptBiayaDlg},
  CFQRRptBiaya in 'Bin\CF\Report\CFQRRptBiaya.pas' {fmCFQRRptBiaya},
  AuditData in 'Bin\AuditData.pas' {fmTrAuditData},
  ARTrBayarBackOffice in 'Bin\AR\Activities\ARTrBayarBackOffice.pas' {fmArTrBayarBackOffice},
  Payroll in 'Bin\Payroll\Payroll.pas' {fmPayroll},
  PayRollQRRptSlipGaji in 'Bin\Payroll\PayRollQRRptSlipGaji.pas' {fmRptSlipGaji},
  QRRptRincianPayroll in 'Bin\Payroll\QRRptRincianPayroll.pas' {fmQRRptRincianPayroll},
  CFTrPiutangInternal in 'Bin\CF\Activities\CFTrPiutangInternal.pas' {fmCFTrPiutangInternal},
  CFQRRptRekapPiutangInternal in 'Bin\CF\Report\CFQRRptRekapPiutangInternal.pas' {fmCFQRRptRekapPiutangInternal},
  CFRptRekapPiutangInternalDlg in 'Bin\CF\Report\CFRptRekapPiutangInternalDlg.pas' {fmCFRptRekapPiutangInternalDlg},
  SAMsCalenderKerja in 'Bin\Setup Acc\Setup\SAMsCalenderKerja.pas' {fmSACalenderKerja},
  ARTrCariModal in 'Bin\AR\Activities\ARTrCariModal.pas' {fmARTrCariModal},
  ARQRRptDetailSummary in 'Bin\AR\Report\ARQRRptDetailSummary.pas' {fmARRptDetailSummary},
  CFTrCreditCard in 'Bin\CF\Activities\CFTrCreditCard.pas' {fmCFTrCreditCard},
  CFTrTransferBalance in 'Bin\CF\Activities\CFTrTransferBalance.pas' {fmCFTrTransferBalance},
  PickDatabase in 'Bin\PickDatabase.pas' {fmPickDatabase},
  CFTrUangMakan in 'Bin\CF\Activities\CFTrUangMakan.pas' {fmCFTrUangMakan},
  CFQRRptUangMakan in 'Bin\CF\Report\CFQRRptUangMakan.pas' {fmCFQRRptUangMakan},
  INRptSNHistoryDlg in 'Bin\Inventory\Report\INRptSNHistoryDlg.pas' {fmINRptSNHistoryDlg},
  ARQRRptPerkenalan in 'Bin\AR\Report\ARQRRptPerkenalan.pas' {fmRptPerkenalan},
  ARMsWilayah in 'Bin\AR\Setup\ARMsWilayah.pas' {fmARMsWilayah},
  APQRRptPenerimaanBarang in 'Bin\AP\Report\APQRRptPenerimaanBarang.pas' {fmQRRptPenerimaanBarang},
  ARMsPelanggan in 'Bin\AR\Setup\ARMsPelanggan.pas' {fmARMsPelanggan},
  RptMultiCetak in 'Bin\RptMultiCetak.pas' {fmRptMultiCetak},
  INQRRptAdjustment in 'Bin\Inventory\Report\INQRRptAdjustment.pas' {fmINQRRptAdjustment},
  ARQrRptPenjPerCustTahun in 'Bin\AR\Report\ARQrRptPenjPerCustTahun.pas' {fmARQRRptPenjPerCustTahun},
  ARQRRptRekapPenjualan in 'Bin\AR\Report\ARQRRptRekapPenjualan.pas' {fmARQRRptRekapPenjualan},
  ARQrRptCetakAmplop in 'Bin\AR\Report\ARQrRptCetakAmplop.pas' {fmARQrRptAmplop},
  CFTrJurnal in 'Bin\CF\Activities\CFTrJurnal.pas' {fmCFTrJurnal},
  CFQRRptBalanceSheet in 'Bin\CF\Report\CFQRRptBalanceSheet.pas' {fmCFQRRptBalanceSheet},
  CFQRRptLabaRugi in 'Bin\CF\Report\CFQRRptLabaRugi.pas' {fmCFQrRptLabaRugi},
  CFTrKKBB1 in 'Bin\CF\Activities\CFTrKKBB1.pas' {fmCFTrKKBB1},
  APPurchaseRequest in 'Bin\AP\Activities\APPurchaseRequest.pas' {fmAPPurchaseRequest},
  APTrPurchaseOrder in 'Bin\AP\Activities\APTrPurchaseOrder.pas' {fmAPTrPurchaseOrder},
  ARRptSales in 'Bin\AR\Report\ARRptSales.pas' {fmARRptSales},
  ARQRRptSales in 'Bin\AR\Report\ARQRRptSales.pas' {fmARQRRptSales},
  ARTRSales in 'Bin\AR\Activities\ARTRSales.pas' {fmARTRSales},
  APQRMaterialReuqest in 'Bin\AP\Report\APQRMaterialReuqest.pas' {fmAPQRMaterialRequest},
  ARQRRptReceiveInv in 'Bin\AR\Report\ARQRRptReceiveInv.pas' {fmARQRRptReceiveInv},
  ARQRRptBuatMR in 'Bin\AP\Report\ARQRRptBuatMR.pas' {fmARQRRptBuatMR},
  ARRptBuatMR in 'Bin\AP\Report\ARRptBuatMR.pas' {fmARRptBuatMR},
  INRptStockHistory in 'Bin\Inventory\Report\INRptStockHistory.pas' {fmINRptStockHistory},
  INQRRptStockHistory in 'Bin\Inventory\Report\INQRRptStockHistory.pas' {fmINQRRptStockHistory},
  ARTrPengReturPenj in 'Bin\AR\Activities\ARTrPengReturPenj.pas' {fmARTrPengReturPenj},
  ARTrPayReturnRep in 'Bin\AR\Activities\ARTrPayReturnRep.pas' {fmARTrPayReturnRep},
  InvoicePenjualan in 'Bin\AR\Report\InvoicePenjualan.pas' {fmInvoicePenjualan},
  PerformaInv in 'Bin\AR\Report\PerformaInv.pas' {fmPerformaInv},
  ARConfirmOto in 'Bin\CF\Activities\ARConfirmOto.pas' {fmARConfirmOto},
  RptVoucher in 'Bin\CF\Report\RptVoucher.pas' {fmRptVoucher},
  ARChangeNoInv in 'Bin\AR\Activities\ARChangeNoInv.pas' {fmARChangeNoInv},
  RptJurnalDay in 'Bin\CF\Report\RptJurnalDay.pas' {fmRptJurnalDay},
  INMsService in 'Bin\Inventory\Setup\INMsService.pas' {fmInMsService},
  ARTRSaldoAwal in 'Bin\AR\Activities\ARTRSaldoAwal.pas' {fmSaldoAwal},
  ARTrReturPenjualan in 'Bin\AR\Activities\ARTrReturPenjualan.pas' {fmARTrReturPenjualan},
  QRRetur in 'Bin\AR\Report\QRRetur.pas' {fmQRRetur},
  CFQRRptBukuBesar in 'Bin\CF\Report\CFQRRptBukuBesar.pas' {fmCFRptBukuBesar},
  CFTrTB in 'Bin\CF\Activities\CFTrTB.pas' {fmCfTrTB},
  PRBlmPO in 'Bin\AP\Report\PRBlmPO.pas' {fmPRBlmPO},
  QRPRBlmPO in 'Bin\AP\Report\QRPRBlmPO.pas' {fmQRPRBlmPO},
  CFRptAdjusmentKurs in 'Bin\CF\Report\CFRptAdjusmentKurs.pas' {fmCFRptAdjustmentKurs},
  QRRptBeliTgl in 'Bin\AP\Report\QRRptBeliTgl.pas' {fmQRRptBeliTgl},
  APRptSupplier in 'Bin\AP\Report\APRptSupplier.pas' {fmApRptSupplier},
  INRptSuratJalanTrf in 'Bin\Inventory\Report\INRptSuratJalanTrf.pas' {fmINRptSuratJalanTrf},
  APRptLapPRBlmRealisasi in 'Bin\AP\Report\APRptLapPRBlmRealisasi.pas' {fmAPRptLapPRBlmRealisasi},
  APRptLaporanPO in 'Bin\AP\Report\APRptLaporanPO.pas' {fmAPRptLaporanPO},
  APBATerima in 'Bin\AP\Report\APBATerima.pas' {fmAPBATerima},
  ImportData in 'Bin\ImportData.pas' {fmImportData},
  ExportImport in 'Bin\ExportImport.pas' {fmExportImport},
  RptTerimaSolar in 'Bin\Inventory\Report\RptTerimaSolar.pas' {fmRptTerimaSolar},
  RptSolar in 'Bin\Inventory\Report\RptSolar.pas' {fmRptSolar},
  QRRptSolar in 'Bin\Inventory\Report\QRRptSolar.pas' {fmQRRptSolar},
  RptBan in 'Bin\Inventory\Report\RptBan.pas' {fmRptBan},
  INRptUnit in 'Bin\Inventory\Report\INRptUnit.pas' {fmRptUnit},
  QRRptUnit in 'Bin\Inventory\Report\QRRptUnit.pas' {fmQRRptUnit},
  APTrOtorisasi in 'Bin\AP\Activities\APTrOtorisasi.pas' {fmAPTrOtorisasi},
  Konfirmasi in 'Bin\Konfirmasi.pas' {fmKonfirmasi},
  APQRPR1 in 'Bin\AP\Report\APQRPR1.pas' {fmAPQRPR1},
  APQRPR2 in 'Bin\AP\Report\APQRPR2.pas' {fmAPQRPR2},
  APQRPR3 in 'Bin\AP\Report\APQRPR3.pas' {fmAPQRPR3},
  APQRMR in 'Bin\AP\Report\APQRMR.pas' {fmAPQRMR},
  INRptStokGudang in 'Bin\Inventory\Report\INRptStokGudang.pas' {fmINRptStokGudang},
  ARQRRptPurchaseOrder in 'Bin\AR\Report\ARQRRptPurchaseOrder.pas' {fmARQRRptPurchaseOrder},
  APPrOtorisasi in 'Bin\AP\Activities\APPrOtorisasi.pas' {fmAPPrOtorisasi},
  PRConfirm in 'Bin\AP\Activities\PRConfirm.pas' {fmPRConfirm},
  PRAction in 'Bin\AP\Activities\PRAction.pas' {fmPRAction},
  APRptPenerimaan in 'Bin\AP\Report\APRptPenerimaan.pas' {fmAPRptPenerimaan},
  APRptPendingBrg in 'Bin\AP\Report\APRptPendingBrg.pas' {fmAPRptPendingBrg},
  APTrKonfirmasiPR in 'Bin\AP\Activities\APTrKonfirmasiPR.pas' {fmAPTrKonfirmasiPR},
  RptSolarDlg in 'Bin\Inventory\Report\RptSolarDlg.pas' {fmRptSolarDlg},
  INRptUnitTgl in 'Bin\Inventory\Report\INRptUnitTgl.pas' {fmINRptUnitTgl},
  APRptLapMR in 'Bin\AP\Report\APRptLapMR.pas' {fmAPRptLapMR},
  INTrKanibal in 'Bin\Inventory\Activities\INTrKanibal.pas' {fmINTrKanibal},
  INQRKanibal in 'Bin\Inventory\Report\INQRKanibal.pas' {fmINQRKanibal},
  INRptKanibal in 'Bin\Inventory\Report\INRptKanibal.pas' {fmINRptKanibal},
  INOtorisasi in 'Bin\Inventory\Activities\INOtorisasi.pas' {fmINOtorisasi},
  INOtoKonf in 'Bin\Inventory\Activities\INOtoKonf.pas' {fmINOtoKonf},
  INTrJadwalDriver in 'Bin\Inventory\Activities\INTrJadwalDriver.pas' {fmINTrJadwalDriver},
  INRptJadwalDriver in 'Bin\Inventory\Report\INRptJadwalDriver.pas' {fmINRptJadwalDriver},
  RptDataTelp in 'Bin\RptDataTelp.pas' {fmRptDataTelp},
  APRptFPP in 'Bin\AP\Report\APRptFPP.pas' {fmAPRptFPP},
  CFOTOFPP in 'Bin\CF\Activities\CFOTOFPP.pas' {fmCFOTOFPP},
  FPPKonfirm in 'Bin\CF\Activities\FPPKonfirm.pas' {fmFPPKonfirm},
  RptHutang in 'Bin\CF\Report\RptHutang.pas' {fmRptHutang},
  ConfirmMR in 'Bin\AP\Activities\ConfirmMR.pas' {fmConfirmMR},
  APRptConfirmMR in 'Bin\AP\Activities\APRptConfirmMR.pas' {fmAPRptConfirmMR},
  RekapConfirmMR in 'Bin\AP\Activities\RekapConfirmMR.pas' {fmRekapConfirmMR},
  MsMaster in 'Bin\AR\Activities\MsMaster.pas' {fmMsMaster},
  ARMsSalesRK in 'Bin\AR\Activities\ARMsSalesRK.pas' {fmARMsSalesRK},
  ConfirmNote in 'Bin\AP\Activities\ConfirmNote.pas' {fmConfirmNote},
  CFRptPOBlmInv in 'Bin\CF\Report\CFRptPOBlmInv.pas' {fmCFRptPOBlmInv},
  Detail in 'Bin\CF\Report\Detail.pas' {fmDetail},
  CFRptFPS in 'Bin\CF\Report\CFRptFPS.pas' {fmCFRptFPS},
  InputNo in 'Bin\CF\Report\InputNo.pas' {fmInputNo},
  ARMsSalesKK in 'Bin\AR\Activities\ARMsSalesKK.pas' {fmARMsSalesKK},
  ARMsSalesDt in 'Bin\AR\Setup\ARMsSalesDt.pas' {fmARMsSalesDt},
  SAMsRekJual in 'Bin\AR\Setup\SAMsRekJual.pas' {fmSAMsRekJual},
  ARQRInvoice in 'Bin\AR\Report\ARQRInvoice.pas' {fmARQRinvoice},
  ARRptInvoice in 'Bin\AR\Report\ARRptInvoice.pas' {fmARRptInvoice},
  INRptPakaiUnit in 'Bin\Inventory\Activities\INRptPakaiUnit.pas' {fmINRptPakaiUnit},
  INRptStokMin in 'Bin\Inventory\Activities\INRptStokMin.pas' {fmINRptStokMin},
  CFGenerate in 'Bin\Inventory\Activities\CFGenerate.pas' {fmCFGenerate},
  CFRptDetailKas in 'Bin\CF\Report\CFRptDetailKas.pas' {fmCFRptDetailKas},
  INRptInventaris in 'Bin\Inventory\Report\INRptInventaris.pas' {fmINRptInventaris},
  QRRptInventaris in 'Bin\Inventory\Report\QRRptInventaris.pas' {fmQRRptInventaris},
  AROtorisasi in 'Bin\AR\Activities\AROtorisasi.pas' {fmAROtorisasi},
  ARKonfirmasi in 'Bin\AR\Activities\ARKonfirmasi.pas' {fmARKonfirmasi},
  QROtorisasi in 'Bin\Inventory\Activities\QROtorisasi.pas' {fmQROtorisasi},
  Control in 'Bin\Inventory\Activities\Control.pas' {fmQC},
  INMsNoUnit in 'Bin\Inventory\Setup\INMsNoUnit.pas' {fmINMsNoUnit},
  INMutasiBan in 'Bin\Inventory\Report\INMutasiBan.pas' {fmINMutasiBan},
  INRptMutasiBan in 'Bin\Inventory\Report\INRptMutasiBan.pas' {fmINRptMutasiBan},
  MTMutasiUnit in 'Bin\MT\Activities\MTMutasiUnit.pas' {fmMTMutasiUnit},
  MTSuratJalan in 'Bin\MT\Activities\MTSuratJalan.pas' {fmMTSuratJalan},
  ARRptHM in 'Bin\AR\Report\ARRptHM.pas' {fmARRptHM},
  ARQRRptHM in 'Bin\AR\Report\ARQRRptHM.pas' {fmARQRRptHM},
  ARQRRptHMUnit in 'Bin\AR\Report\ARQRRptHMUnit.pas' {fmARQRRptHMUnit},
  ARQRRptHMBulan in 'Bin\AR\Report\ARQRRptHMBulan.pas' {fmARQRRptHMBulan},
  ARFPS in 'Bin\AR\Activities\ARFPS.pas' {fmARFPS},
  InputFPS in 'Bin\AR\Activities\InputFPS.pas' {fmInputFPS},
  MTRptMutasiUnit in 'Bin\MT\Report\MTRptMutasiUnit.pas' {fmMTRptMutasiUnit},
  MTQRRptMutasiUnit in 'Bin\MT\Report\MTQRRptMutasiUnit.pas' {fmMTQRRptMutasiUnit},
  LokasiUnit in 'Bin\MT\Report\LokasiUnit.pas' {fmLokasiUnit},
  ARQRRptKaryawan in 'Bin\AR\Report\ARQRRptKaryawan.pas' {fmARQRRptKaryawan},
  ARRptKaryawan in 'Bin\AR\Report\ARRptKaryawan.pas' {fmARRptKaryawan},
  HRPromotion in 'Bin\HR\HRPromotion.pas' {fmHRPromotion},
  MTMsService in 'Bin\MT\Setup\MTMsService.pas' {fmMTMsService},
  HRRptPromotion in 'Bin\HR\HRRptPromotion.pas' {fmHRRptPromotion},
  HRQRRptPromotion in 'Bin\HR\HRQRRptPromotion.pas' {fmHRQRRptPromotion},
  HRMsSalary in 'Bin\HR\HRMsSalary.pas' {fmHRMsSalary},
  MsAbsensi in 'Bin\HR\MsAbsensi.pas' {fmMsAbsensi},
  OPTrWorkUnit in 'Bin\OP\Activities\OPTrWorkUnit.pas' {fmOPTrWorkUnit},
  OPTrProduksi in 'Bin\OP\Activities\OPTrProduksi.pas' {fmOPTrProduksi},
  INMsSites in 'Bin\Inventory\Setup\INMsSites.pas' {fmINMsSites},
  OPRptProduksi in 'Bin\OP\Report\OPRptProduksi.pas' {fmOPRptProduksi},
  OPRptProduksiDet in 'Bin\OP\Report\OPRptProduksiDet.pas' {fmOPRptProduksiDet},
  OPRptProduksiHaulSum in 'Bin\OP\Report\OPRptProduksiHaulSum.pas' {fmOPRptProduksiHaulSum},
  OPRptProduksiHaulDet in 'Bin\OP\Report\OPRptProduksiHaulDet.pas' {fmOPRptProduksiHaulDet},
  ARMsJenisInvoice in 'Bin\AR\Setup\ARMsJenisInvoice.pas' {fmARMsJenisInvoice},
  HRRptSumAbsen in 'Bin\HR\HRRptSumAbsen.pas' {fmHRRptSumAbsen},
  INRptStockMinimum in 'Bin\Inventory\Report\INRptStockMinimum.pas' {fmINRptStockMinimum},
  OPRptWorkUnit in 'Bin\OP\Report\OPRptWorkUnit.pas' {fmOPRptWorkUnit},
  OPWorkUnit in 'Bin\OP\Activities\OPWorkUnit.pas' {fmOPWorkUnit},
  SFTrClearance in 'Bin\SF\Activities\SFTrClearance.pas' {fmSFTrClearance},
  SFRptSafetyItem in 'Bin\SF\Report\SFRptSafetyItem.pas' {fmSFRptSafetyItem},
  SFRptPakai in 'Bin\SF\Report\SFRptPakai.pas' {fmSFRptPakai},
  SFRptClearance in 'Bin\SF\Report\SFRptClearance.pas' {fmSFRptClearance},
  APRptBayarPO in 'Bin\AP\Report\APRptBayarPO.pas' {fmAPRptBayarPO},
  CFRptJurnal in 'Bin\CF\Report\CFRptJurnal.pas' {fmCFRptJurnal},
  INRptUnitNew in 'Bin\Inventory\Report\INRptUnitNew.pas' {fmRptUnitNew},
  APTrRental in 'Bin\AP\Activities\APTrRental.pas' {fmAPTrRental},
  INRptJadwalDriver2 in 'Bin\Inventory\Report\INRptJadwalDriver2.pas' {fmINRptJadwalDriver2},
  INRptMsItem2 in 'Bin\Inventory\Activities\INRptMsItem2.pas' {fmINRptMsItem2},
  INRptMsCompartment in 'Bin\Inventory\Report\INRptMsCompartment.pas' {fmINRptMsCompartment},
  AROtoAdjustment in 'Bin\AR\Activities\AROtoAdjustment.pas' {fmAROtoAdjustment},
  ARTrSalesKontrak in 'Bin\AR\Activities\ARTrSalesKontrak.pas' {fmARTrSalesKontrak},
  ARKonfirmasiInv in 'Bin\AR\Activities\ARKonfirmasiInv.pas' {fmARKonfirmasiInv},
  AROtoSalesInv in 'Bin\AR\Activities\AROtoSalesInv.pas' {fmAROtoSalesInv},
  APOtoFPP in 'Bin\AP\Activities\APOtoFPP.pas' {fmAPOtoFPP},
  APOtoKonsinyasi in 'Bin\AP\Activities\APOtoKonsinyasi.pas' {fmAPOtoKonsinyasi},
  KonfirmasiKonsinyasi in 'Bin\AP\Activities\KonfirmasiKonsinyasi.pas' {fmKonfirmasiKonsinyasi},
  INMsLayout in 'Bin\Inventory\Setup\INMsLayout.pas' {fmINMsLayout},
  INRptStockAkhir in 'Bin\Inventory\Report\INRptStockAkhir.pas' {fmINRptStockAkhir},
  APRptPOBlmTerima in 'Bin\AP\Report\APRptPOBlmTerima.pas' {fmAPRptPOBlmTerima},
  OPRptBOD in 'Bin\OP\Report\OPRptBOD.pas' {fmOPRPtBOD},
  SAMsPT in 'Bin\Setting\Setup\SAMsPT.pas' {fmSAMsPT};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TdmMain, dmMain);
  Application.CreateForm(TfmLogin, fmLogin);
  Application.CreateForm(TfmKeyPadSC, fmKeyPadSC);
  Application.CreateForm(TfmOPRPtBOD, fmOPRPtBOD);
  Application.CreateForm(TfmSAMsPT, fmSAMsPT);
  if not (dmMain.dbConn.Connected) or (fmLogIn.ShowModal = mrAbort) then
  begin
     Application.Terminate;
     Exit;
  end;
  Application.Run;
end.
